#!/usr/bin/env php
<?php
include __DIR__.'/vendor/autoload.php';

$options = getopt('f:u:p:c:');
$file = $options['f'];
$username = $options['u'];
$password = $options['p'];
$caption = $options['c'];

if (is_null($file) || is_null($username) || is_null($password)) {
  print 'Bad arguments\n';
  print 'Usage: instagram -f <file> -u <username> -p <password> -c <caption>';
  exit(1);
}

$debug = false;
//////////////////////
$i = new \InstagramAPI\Instagram($username, $password, $debug);
try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit(1);
}
try {
    $i->uploadVideo($file, $caption);
    $feed = $i->getSelfUserFeed();
    $id = $feed['items'][0]['code'];
    echo "https://www.instagram.com/p/$id/";
    exit(0);
} catch (Exception $e) {
    echo $e->getMessage();
    exit(1);
}
