#!/usr/bin/env php
<?php
include __DIR__.'/vendor/autoload.php';

$options = getopt('f:u:p:');
$file = $options['f'];
$username = $options['u'];
$password = $options['p'];

if (is_null($file) || is_null($username) || is_null($password)) {
  print 'Bad arguments\n';
  print 'Usage: instagram -f <file> -u <username> -p <password>';
  exit(1);
}

$debug = false;
$caption = '';

//////////////////////
$i = new \InstagramAPI\Instagram($username, $password, $debug);
try {
    $i->login();
} catch (Exception $e) {
    $e->getMessage();
    exit();
}
try {
    $i->uploadVideo($file, $caption);
} catch (Exception $e) {
    echo $e->getMessage();
}
